# runtime: python
# env: flex
# entrypoint: gunicorn -b :$PORT main:app
# runtime_config:
#     python_version: 3.7

# manual_scaling:
#     instances: 1
# resources:
#     cpu: 1
#     memory_gb: 5
#     disk_size_gb: 20

runtime: custom
env: flex

manual_scaling:
    instances: 1
resources:
    cpu: 1
    memory_gb: 5
    disk_size_gb: 20